### ISSUE TITLE
Activity/dht11 sensor - Flogo Web UI failed installation.

### ISSUE THREAD

**Issue by shaliniGovindaNayak** [mmussett/flogo-components#1]
I tried to install the dht sensor activity using "https://github.com/mmussett/flogo-components/activity/sensor_dht " on Flogo web UI but getting a installation failed msg.

**Comment by mmussett** [comment]
I switched to using a different third-party library to one that uses C as it didn't work with RPI Zero boards. I may be able to create a another version that uses the pure Golang library that would work in the UI. You can still use the Flogo CLI to build and add the activity directly in to your flogo.json.
