### ISSUE TITLE
any plans to create a Trigger

### ISSUE THREAD

**Issue by JGrotex** [mmussett/flogo-components#3]
any plans to create a Flogo Trigger to receive EMS Messages and start a flow?
Should be feasible, or?

**Comment by jkoenig72** [comment]
Would be very useful!

**Comment by mmussett** [comment]
> any plans to create a Flogo Trigger to receive EMS Messages and start a flow?
> Should be feasible, or?

It's very feasible, just haven't had the bandwidth in my personal life to do it. Maybe spend a couple of hours this week and knock one up for you guys.

**Comment by pillarbg** [comment]
> It's very feasible, just haven't had the bandwidth in my personal life to do it. Maybe spend a couple of hours this week and knock one up for you guys.

Started some work on it using  your sample for an EMS activity.  Need to figure out how to forward the payload to the flow.

**Comment by mmussett** [comment]
Added EMS trigger.

**Comment by mmussett** [comment]
> > It's very feasible, just haven't had the bandwidth in my personal life to do it. Maybe spend a couple of hours this week and knock one up for you guys.
> 
> Started some work on it using your sample for an EMS activity. Need to figure out how to forward the payload to the flow.

EMS trigger is now available.
